const PATS_ON_THE_BACK = [
  "Well done, partner. Now put your feet up and relax.",
  "Great work, champ. Time to kick back and unwind.",
  "Nice shootin', cowboy. Now go take 'er easy.",
  "Excellent effort, sport. Now rest up and chill out.",
  "Bravo, maestro. Now enjoy some well-deserved downtime.",
  "Splendid job, old sport. Now take a load off and relax.",
  "Good show, mate. Now take a breather and enjoy yourself.",
  "Top-notch, ace. Now go easy and relax a bit.",
  "Terrific, kiddo. Now take a break and take it easy.",
  "Nicely done, buddy. Now go ahead and relax.",
  "Slay, bestie. Now go chillax.",
  "Fire job, fam. Time to vibe out.",
  "You crushed it, dude. Now go catch some z's.",
  "That's lit, squad. Now take a breather.",
  "You ate that, queen. Now take it easy.",
  "W, bro. Now go chill and recharge.",
  "Dope work, gang. Time to kick back.",
  "Big flex, my guy. Now go relax.",
  "You killed it, sis. Now go get some R&R.",
  "Epic win, homie. Now take it easy and unwind.",
  "Arrr, well done, matey! Now go rest yer sea legs.",
  "Great work, ye scallywag! Now take a load off and relax.",
  "Ye did a fine job, buccaneer! Now go enjoy some shore leave.",
  "Excellent, ye salty dog! Now go swab the deck o' rest.",
  "Ye nailed it, ye landlubber! Now go take a breather.",
  "Fine shootin', swashbuckler! Now go take 'er easy.",
  "Ye be a true pirate, mate! Now go rest in yer hammock.",
  "Top marks, ye sea rover! Now go sip some grog and relax.",
  "Well done, corsair! Now take a spell and relax.",
  "Ye did splendid, privateer! Now go take a well-earned break.",
  "Nice one, bruv. Now go grab a cheeky rest.",
  "Well sorted, mate. Time to have a proper chill.",
  "Good effort, pal. Now have a sit down and relax.",
  "Smashed it, yeah? Now go have a cuppa and unwind.",
  "You done good, innit. Now go kick back and relax.",
  "Bang on, geezer. Now go chill and have a breather.",
  "Top job, luv. Now go chill out and take it easy.",
  "Sound work, my friend. Now go have a natter and relax.",
  "Sorted, fam. Now go put your feet up and have a rest.",
  "Proper job, matey. Now go take a breather and enjoy yourself.",
  "You nailed it, guv. Now go have a proper rest.",
  "Great job, dapper. Now go chill and have a break.",
  "Nice one, bruv. Now go take a load off.",
  "Well done, mate. Now go have a rest and chill.",
  "You smashed it, my old chum. Now go relax a bit.",
  "You did well, mate. Time to have a little chill-out.",
  "Spot on, buddy. Now go kick back and relax.",
  "Good show, mate. Now have a breather and relax.",
  "You did a top job, mate. Now go and chill out.",
  "Nice work, mucker. Now take a breather and rest up.",
  "Dig it, cat. Now lay back and let the groove settle.",
  "Swingin’ job, daddy-o. Time to mellow out and relax.",
  "You played it cool, hep cat. Now kick back and enjoy the vibe.",
  "That was smooth, jazzman. Now catch some downtime and unwind.",
  "You nailed that solo, cool cat. Now ease into some chill time.",
  "Great licks, feline friend. Now take a breather and feel the rhythm.",
  "You really jazzed it up, man. Now go soak in some relaxation.",
  "That was the real deal, hipster. Now lay low and take it easy.",
  "Fantastic riff, groove master. Time to unwind and let the beat drop.",
  "You hit all the right notes, cool cat. Now chill out and savor the calm.",
  "Smooth performance, jazz cat. Now kick back and soak up some relaxation.",
  "Solid session, hep friend. Now take a moment to catch your breath.",
  "You really swung it, cat. Now let yourself groove into relaxation.",
  "You played it slick, daddy. Now go find some mellow time.",
  "Nice solo, cool jazz cat. Now ease into a well-deserved rest.",
  "You hit it out of the park, swingster. Now take a timeout and chill.",
  "That was prime, man. Now go relax and let the music fade.",
  "Excellent riffing, jazz ace. Now unwind and let the smooth vibes roll.",
  "You played it right, hepster. Now go ease into some relaxation.",
];

export function getPatOnTheBack() {
  return PATS_ON_THE_BACK[Math.floor(Math.random() * PATS_ON_THE_BACK.length)];
}
