const captions = [
  "when you know the bartender",
  "when you know the bartender",
  "when you don't know the bartender",
  "when you don't know the bartender",
  "when you're not sure if you know the bartender",
  "when you're not sure if you don't know the bartender",
  "when the music is hittin",
  "when the music is hittin",
  "when the music is hittin",
  "me n the boys",
  "hello there",
  "hello there",
  "This is the way.",
  "It is known.",
  "me n the boys",
  "me n the fellas",
  "me n the gang",
  "just rolled up",
  "just rolled up",
  "me n the girls",
  "me n the bitches",
  "hood rat stuff with my friends",
  "feelin cute, might delete later",
  "If found, please provide with beer",
  "If found, please provide with wine",
  "If found, please provide with weed",
  "I'm not drukn",
  "hi mom",
  "when the edibles hittin",
  "oh word",
  "rachael please call me",
  "🥸",
  "🔥🔥🔥",
  "night feels right",
  "surrounded by legends",
  "sound on",
  "IYKYK",
  "when the whole crew is here",
  "pov: just found your new bae",
  "pov: just found your new favorite band",
  "turns out i CAN party",
  "allllllrighty then",
  "the beat that brings us together",
  "oh oh it's maaaaagic",
  "energy level: maximum",
  "🤠",
  "🤡",
  "me n you, n you n me",
  "This song's about me",
  "This song's about you",
  "This song's about us",
  "well well well...",
  "kisscam",
];

export function getRandomCaption() {
  return captions[Math.floor(Math.random() * captions.length)];
}
